#!/bin/bash

urls=("https://lineasmetro.com/estacion-tren-ligero-juarez" "https://lineasmetro.com/estacion-tren-ligero-plaza-universidad" "https://lineasmetro.com/estacion-tren-ligero-san-juan-de-dios" "https://lineasmetro.com/estacion-tren-ligero-belisario-dominguez" "https://lineasmetro.com/estacion-tren-ligero-oblatos" "https://lineasmetro.com/estacion-tren-ligero-cristobal-de-onate" "https://lineasmetro.com/estacion-tren-ligero-san-andres" "https://lineasmetro.com/estacion-tren-ligero-san-jacinto" "https://lineasmetro.com/estacion-tren-ligero-la-aurora" "https://lineasmetro.com/estacion-tren-ligero-tetlan")

echo "Name,Latitude,Longitude" > "Línea 2.csv"

for url in "${urls[@]}"
do
	name="$(echo "$url" | grep -Pio '(?<=estacion-tren-ligero-).+')"
	wget -O index.html "$url"

	if [[ $? != 0 ]];
	then
		echo "$url" >> urls_with_errors.txt
	fi

	coordinates="$(cat index.html | grep 'google.com' | grep -Po '(?<=!2d)[^!]+!3d[^!]+')"

	longitude="$(echo "$coordinates" | grep -Po '(?<=!3d).+')"
	latitude="$(echo "$coordinates" | grep -Po '^[^!]+')"

	echo "${name^},${longitude},${latitude}" >> "Línea 2.csv"

	rm index.html
done
